### ISSUE TITLE
BootCamp help

### ISSUE THREAD

**Issue by msedek** [osy86/HaC-Mini#103]
Im pretty new to hackintoshing and trying to bootcamp windows, don't know if thats the best or only way to dual boot my pc, the thing is that I have 1 nmve evo 970 with my mojave full with everything working 100% working with the lastest hac-mini 2.3, and I also have an nvme samsun evo 960 installed and clean... I want windows to be and live in that second drive, got also a 8gb pendrive clean in the machine, I start the bootcamp assistant.. it asks me where do i want to install windows, I go for the clean samsun evo 960 as it is available as option.. then it downloads some stuff.. creates a "wininstall" partition but never asking for the USB, followed the hac-mini guide and deleted the drivers and rebooted.. nothing happens.. it does not installs and don't know what to do.. theres no guides around this case

**Comment by osy86** [comment]
Hi, this site is for tracking issues. If you want support, the hackintosh community can be helpful. Please try insanelymac or /r/hackintosh or their discord.

**Comment by PeterBurner** [comment]
hi guys

Im currently facing the same issue
The Boot Camp Assistant creates the partitions `WinInstall` (ExFAT) and `BOOTCAMP` (NTFS)
It even tries to automatically boot the installer (no chance to delete drivers before that) but only a black screen appears and nothing else happens (Ctrl+Alt+Del triggers reboot to MacOS)
OpenCore boot picker shows:
`1. EFI` --> retruns to boot picker after ~1 second
`2. MacOS` --> boots MacOS
`3. Recovery` --> boots recovery
`4. Reset NVRAM`

I assume option 1 should boot the Installer? ¯\_(ツ)_/¯

I tried blessing the `WinInstall` volume from recovery as discribed here: [link](https://discussions.apple.com/thread/7265423)
```
bless --folder /Volumes/WinInstall --file /Volumes/WinInstall/bootmgr.efi --setBoot
```
But after a reboot the same black screen as before appears
Ctrl+Alt+Del triggers reboot to black screen
After choosing MacOS from OpenCore boot picker once everyting is back to normal

@lmshsqlc did you find a solution for this?

@osy86 since having two M.2 SSDs in a Hades Canyon is a valid and common use case, instructions on how to make this work should be included in the install guide

**Comment by msedekhyh** [comment]
You dont need anuthing from bootcamp, just create a regular windows install usb, diaconnect the macos drive(if you are using 2 drives) install windows nornally, once installation finishes, reconnect the macos drive, turn on your pc  disconnect the usb and spam alt until you get the hac mini boot menú, there you can either select macos yo boot or continúe to windowds

**Comment by PeterBurner** [comment]
@msedekhyh thanks for the tip
works like a charm
