### ISSUE TITLE
Any way to start up NUC without display plugged in？

### ISSUE THREAD

**Issue by errorstack** [osy86/HaC-Mini#110]
Today I turned on the power of my NUC, the led light of the power was on, but system didn’t start up,  and there’s not any display signal and I even could not get into the BIOS.

Finally I found the reason is NUC cannot start up without display plugged in, and the miniDP slot sometimes cannot be detected during booting, so the nuc cannot start up.  I plugged the display into the HDMI slot and plugged out the power and replugged in. System started up normally. Then I plugged display back into the miniDP slot, everything’s fine.

 So, to avoid this, is there any way to start up NUC without display plugged in?

**Comment by osy86** [comment]
Try pressing some keyboard keys like Enter and Spacebar. There might be some bios message.

**Comment by SpookHCK** [comment]
You could always try one of these:
https://www.amazon.com/dp/B01EK05WTY/ref=cm_sw_em_r_mt_dp_U_s8AWDb8DZJNEE
They plug into a HDMI port and simulate a monitor...

**Comment by errorstack** [comment]
> You could always try one of these:
> https://www.amazon.com/dp/B01EK05WTY/ref=cm_sw_em_r_mt_dp_U_s8AWDb8DZJNEE
> They plug into a HDMI port and simulate a monitor...

OK. Thank you.

**Comment by osy86** [comment]
@errorstack I don't have any issues running it without a display. Here's my setup

1. Install Duet app (required since Sidecar only works as secondary display, Duet/Luna lets you use it as primary)
2. Power on NUC
3. Wait ~10 seconds, then if you have FileVault enabled, you need to blindly type in the password. Press the first character of your username to select it (if you have multiple accounts). Otherwise it will be selected automatically. Then blindly type in your password.
4. If the password is correct/no filevault then you should see the keyboard turn off and on again indicating that OSX is booted.
5. If you don't have FileVault, you now need to login. Same instructions as in 3.
6. Open Duet on the iPad and after ~30 seconds, you should see Duet connect.

If you don't care for GUI, then you can use SSH instead. Or even VNC. I don't see any issue with OSX booting without a display.

**Comment by errorstack** [comment]
> @errorstack I don't have any issues running it without a display. Here's my setup
> 
> 1. Install Duet app (required since Sidecar only works as secondary display, Duet/Luna lets you use it as primary)
> 2. Power on NUC
> 3. Wait ~10 seconds, then if you have FileVault enabled, you need to blindly type in the password. Press the first character of your username to select it (if you have multiple accounts). Otherwise it will be selected automatically. Then blindly type in your password.
> 4. If the password is correct/no filevault then you should see the keyboard turn off and on again indicating that OSX is booted.
> 5. If you don't have FileVault, you now need to login. Same instructions as in 3.
> 6. Open Duet on the iPad and after ~30 seconds, you should see Duet connect.
> 
> If you don't care for GUI, then you can use SSH instead. Or even VNC. I don't see any issue with OSX booting without a display.

It happened twice in the past 10 days, and I can't reproduce it again. It's probably not a display issue. Thank you anyway.

**Comment by osy86** [comment]
I think it’s probably a thunderbolt issue. I’ve experienced it even with a display. If it happens you just have to unplug the power and replug it. I don’t restart often so it’s not a big issue for me.
