### ISSUE TITLE
No sleep working

### ISSUE THREAD

**Issue by adriavidal** [osy86/HaC-Mini#232]
any bios (have tried witht the default suggestion) or config suggestion for sleep ?
Mine goes to sleep (power button blinks), screen gooes to black, but impossible to return to live.

Energy settings checked
prevent sleep when screen shut down
put disk to sleep when possible
ethernet acces enable
start after electric power cut
enable power nap

Screen connected via mini-DP to DP BenQ EL2870U,tried with a thunderlbolt to DP to an Dell screen with the same end.

Can give me some advice or tips ?

**Comment by osy86** [comment]
Does it wake up but screen stays dark? Or does it not even wake up?

**Comment by adriavidal** [comment]
it never wakes, no keyboard acces (key lock green), no ping from another computer or lan or VNC

**Comment by osy86** [comment]
Are you using the latest hac mini package?

**Comment by adriavidal** [comment]
Yes just upgraded today to it.
Can try to produce some logs

**Comment by adriavidal** [comment]
Any bios special setting at s4/s5 ?
Somone can share additional screen config not from the originat BIOS screenshot's?
And at energy settings configuration panel?

**Comment by ilderaj** [comment]
Same here. Have updated to the latest hac mini. 

I'm using an LG 4k display through HDMI port. It flickers occasionally which is acceptable. 

When it goes to sleep it does not wake up properly by tapping the USB keyboard or the mouse. The hard drive does wake up as I can see the green light, but the display does not. 

When the screen is turned off manually by pressing the power button for like 20 minutes, it doesn't wake up either. 

I have tried the blue USB port on the front, it doesn't seem to work. 

Is it because I'm using LAN instead of WiFi?

**Comment by adriavidal** [comment]
Any suggestion about bios os mac preferences setting have to check? any console command to see if hiberntation is enabled ?

**Comment by ilderaj** [comment]
> Are you using the latest hac mini package?

I'm checking this instruction. 

https://forum.amd-osx.com/viewtopic.php?t=9294

The guy mentioned the USB fix might not work with USB 2.0 devices plugging into the USB 3.0 ports.   If this is the issue, does it mean we should use bluetooth mouses and keyboards?

**Comment by psychic69** [comment]
Power Nap does not work properly on my NUC.  If it goes into deep sleep, it panic and upon panic my bluetooth module disappears (imagine my keyboard going away).  

I cannot get my sleep to work in any combination except scheduling a shutoff.  I figured out what was keeping it alive during the day (folding @ home), but now since the latest supplemental update (10.15.4) (and update of hacmini) sleep doesn't work at all again.

I would disable put hard drive to sleep, power nap, prevent sleep at a minimum.  Schedule a shut down and see if that works at least.  I also turned off screen time and that would (previously) allow me to sleep on a schedule.

Go to activity monitor, energy tab and see if you have apps keeping the machine awake

**Comment by adriavidal** [comment]
I've disabled everthing at OS' energy settings, only restart after power cut.
Computer goes to sleep, screen's go to sleep, only 2 front led green on , power button on (not dimming).

Impossible to put it on (keyboard ubs not responding), plug an addtional mouse by usb, nothing.
Keep power button on for 5 seconds, computer goes off, and when on again system report a crash.

Sleep Wake failure in EFI

Failure code:: 0xffffffff 0x0000001f

Please IGNORE the below stackshot

================================================================
Date/Time:        2020-04-14 08:21:01 +0200
OS Version:       ??? ??? (Build ???)
Architecture:     x86_64
Report Version:   29

Data Source:      Stackshots
Shared Cache:     0x1c63000 E5D7B9BB-C0B1-3A6B-BC91-07DB07DF4C8B

Event:            Sleep Wake Failure
Duration:         0.00s
Steps:            1

Boot args:        alcid=11 -disablegfxfirmware shikigva=32 shiki-id=Mac-BE088AF8C5EB4FA2

Time Awake Since Boot: 26s

**Comment by ilderaj** [comment]
My 4K monitor only has an HDMI and a DP port.  The mentioned issue happened when using an HDMI to HDMI cable. Now I have switched to a USB-C to DP cable, the problem seems to be solved.

**Comment by adriavidal** [comment]
> My 4K monitor only has an HDMI and a DP port. The mentioned issue happened when using an HDMI to HDMI cable. Now I have switched to a USB-C to DP cable, the problem seems to be solved.

Bad luck to me, using dual monitor running via mini-DP to DP and usb-c to DP. Could you post your bios setting related to s4/s5 and energy settings.

Will try running only 1 monitor when got you setting if possible. thanks

**Comment by adriavidal** [comment]
tried only 1 monitor usb-C to DP same issue. Set computer to sleep. Nuc goes to sleep (lights fade in /fade out).

push 1 key on usb keyboard, try to go out from sleep but no screen don't come out from sleep.
Have to force shutdown with button. And got a message on POST. 

Bios has detected unsuccesful POST.
Y to enter setup N no cancel and attempt to boot

And when login to mac the same Sleep Wake failure in EFI warning.

Please share your BIOS energy setting.

Is the final piece to make these build a perfect one

**Comment by osy86** [comment]
Is the power light on? Did you choose "Native Thunderbolt" or "Legacy Thunderbolt" install option?

**Comment by adriavidal** [comment]
When is in stand by the power button pulsates, then i press a key on keyboard and it seems to try to wake up (pulsate finish), but screen don't even try to go out of energy saving state.
i choosed legacy.

Thanks again

**Comment by ilderaj** [comment]
> > My 4K monitor only has an HDMI and a DP port. The mentioned issue happened when using an HDMI to HDMI cable. Now I have switched to a USB-C to DP cable, the problem seems to be solved.
> 
> Bad luck to me, using dual monitor running via mini-DP to DP and usb-c to DP. Could you post your bios setting related to s4/s5 and energy settings.
> 
> Will try running only 1 monitor when got you setting if possible. thanks

No additional bios settings rather than the HacMini installation guidance. Have turned off Power Nap in system preferences though.

**Comment by adriavidal** [comment]
ok, my machine seems to be an alien
