### ISSUE TITLE
after post hangs after reboot -- thunderbolt 3 display.

### ISSUE THREAD

**Issue by JeffreyVIP** [osy86/HaC-Mini#258]
It is intel hades NUC(NUC8i7HVB) with latest BIOS version(0059).

Everytime I reboot the machine, it always hang after post, only a mouse arrow displayed in the center of the screen. I can do nothing except forcely power-off the NUC.

 

And, hanging repeats until I unplug and plug in thunderbolt 3 display(LG 5K).

To be more precise, if 'BIOS Setup Auto-Entry' is enabled, hangs occurs right after pressing ESC key and before OpenCore boot menu is displayed.

1. There is no issue if only HDMI display connected.
2. It occurs only when only thunderbolt 3 display connected.
3. It won't occur if {Thunderbolt Security Level} sets to DP++ only mode, but embeded speaker&camera of display will lost.
4. After restore(unplug and plug thunderbolt 3 display), it won't occur if shutdown action instead of restart.
5. It occurs no matter thunderbolt patch is applied or not (AKA legacy or native mode).

**Comment by hepto** [comment]
I think I also have symptoms related to this issue, with a 24" LG UltraFine 4k, and the native Thunderbolt patch.

Reboot is hit and miss.  Sometimes on reboot I will see the POST / Intel logo and it will boot to macOS fine.  Sometimes it will show a blank screen until right at the last second then the macOS login screen appears.

But quite frequently I get a blank screen and the NUC appears to be doing nothing - the SSD LED light stays unlit, fans are down.

I am then forced to boot with an HDMI monitor in it will always boot to that monitor, but sometimes the LG won't come on at all, though the internal USB speakers hub are recognised, so it is just the display aspect that is not working.

To resolve that I have to power down and completely remove the power to the NUC, then it will boot up again.

It's a little bit annoying as I have to keep an HDMI monitor around just in case I can't get it to boot, but because it is blank I don't know at what stage it is hanging.

I think sometimes it is on POST it hangs, other times I think it is going to the OpenCore menu and sitting there waiting to be told what to boot.

At no point does it appear to fully boot without a monitor attached though - it either hangs as described, or will get to the login screen and either the LG or the other HDMI screen will be working.

I haven't tested this, but I did not notice this before I applied the Thunderbolt patch, but then the monitors speakers were not supported.  Also, I am not actually using a Thunderbolt cable, but a USB-C cable - I'll see if I can get one (though they are pricey at normal lengths!).

TBH I don't reboot frequently so I can live with it but happy to do some troubleshooting if needed.

**Comment by JeffreyVIP** [comment]
@hepto 
I observe the same experience as you!
You won's see the whole boot process if native thunderbolt patch is applied, but with legacy mode you can. But in both modes you will hit boot hangs issue after system restart.

**Comment by osy86** [comment]
Yeah I've experienced this a few times. Unfortunately there isn't much to do since it's an issue with Intel's garbage tier firmware. I mostly don't restart unless for updates and if I do restart, I would power off, remove the power cord, wait 5 seconds, plug it back in. That should reset the TB ports.

**Comment by JeffreyVIP** [comment]
@osy86 
fabulous word 'garbage tier firmware', it is true that BIOS made by intel is much worse than ones from Gigabytes or Asus.

A topic logged in intel support communitiy.
[Intel Support Community Case](https://forums.intel.com/s/question/0D50P00004fLcfnSAC/after-post-hangs-after-reboot-hades-nuc-thunderbolt-3-display)

@hepto 
Can you comments the topic with your experience so that Intel can put more emphasis on the issue?

**Comment by hepto** [comment]
@osy86 do you think there would be any merit in using a Thunderbolt cable instead of a USB cable?

I don't really understand it - I'm using the monitor with a USB cable, but in System Report it shows the display connected via Thunderbolt.  I don't know if that means that it is run over Thunderbolt but over the USB cable (if that is even possible - maybe at a reduced data rate?), or it is simply the way it is reported by macOS and really it is all USB transmission.

The monitor itself supports both Thunderbolt and USB-C connections, and as I don't have any downstream Thunderbolt devices, I can't see the point of getting a Thunderbolt cable unless it would help ensure the monitor became active on boot.  Any advice please?

**Comment by osy86** [comment]
Well idk but I have a LG 5K and I use the TB3 cable and it works fine for me (aside from the flickers). I do get reboot hangs sometimes though.

**Comment by hepto** [comment]
For any visitors from a search - to answer the question about whether the cable will matter for this particular symptom - the answer is 'no' as suspected!

I ended up getting a certified Thunderbolt 3 cable but no change.  This then made me discover that a good quality USB-C cable will 'carry' a Thunderbolt signal anyway, but most likely at the 20Gbps speed depending on the length of the cable.  You can tell this in System Report both under Thunderbolt (check the speed) and Graphics/Displays and the Connection Type.  (Which is funny as I got a discount on my monitor because the Thunderbolt cable was missing, so they dropped in a USB-C cable instead, and now it turns out it functioned the same way!  But I just wasted that discount on purchasing a Thunderbolt cable anyway ...)

There is still a question about whether an ACTIVE Thunderbolt 3 cable at 40Gbps (which doesn't support USB at all) will make any difference - but those cables are rare and/or expensive and I doubt it would.
