### ISSUE TITLE
Is there a way to restore BIOS motherboard information to NUC defaults?

### ISSUE THREAD

**Issue by HorstBrack75** [osy86/HaC-Mini#265]
My system identifies as:

Intel Macmini8,1
BIOS
Version
1037.80.53.0.0
Date
1/17/2020
MOTHERBOARD
Manufacturer
Intel Corporation
Model
Mac-XXXXXXXXXXXXXXXX (My board id)
Version
Macmini8,1

This seems to confuse Intel Driver Support Assistant. 
I keep getting a notification that there would be an update for Intel® HD Graphics 630. The update then cannot be installed.

I did not get offered the latest BIOS, I had to download it manually.

Is there a way to (at least temporarily) put back the NUC8I7HVK motherboard info?

I already tried NVRAM reset, but it still identifies as Macmini8,1

**Comment by osy86** [comment]
You need to boot into Windows without using OpenCore. An easy way is to open EFI Shell and run windows' `\EFI\Microsoft\boot\bootmgfw.efi` in the EFI partition.

**Comment by hepto** [comment]
I'm not sure this is your issue @HorstBrack75 , as I have this same symptom but I am not using OpenCore to boot to Windows.

I think it's because the driver offered by Intel Driver Support is a generic driver, so the installer rejects the NUC as being a valid target, instead requiring the custom one.  Well, that was the error message last time I checked, but it used to be fine, so if you can get round it I'll be interested too!

**Comment by HorstBrack75** [comment]
After resetting NVRAM and booting withou OpenCore, the system now identifies as:

Version
HNKBLi70.86A.0059.2019.1112.1124
Date
11/12/2019
MOTHERBOARD
Manufacturer
Intel Corporation
Model
Unknown
Version
J68196-503

The Model "Unknown" still bothers me, but at least I could now finally install igfx_win10_100.8190 and the intel updater does no longer offer an update.
