### ISSUE TITLE
 Metal , do not display   Feature set macOS GPUFamily2 v1

### ISSUE THREAD

**Issue by gaowenzhen** [osy86/HaC-Mini#42]
Thanks osy86 share, found the latest version 1.4.1，
Graphics card properties, Metal , do not display   Feature set macOS GPUFamily2 v1，

version 1.3
![image](http://editor.art2print.cn/CHILI/test/download.aspx?type=full&apiKey=KgaM9cik_P97s8Wq67yvZyzCawLCxzVBWzQ7xBETacqxTSYyQGVt7E0o0nZnPlPGkM5JoVlsVmL5sZ9m1t2UeQ==&id=425d2ed0-51ae-4c0d-a606-a6bce07bc9d6&resourceName=Assets)

version 1.4.1
![image](http://editor.art2print.cn/CHILI/test/download.aspx?type=full&apiKey=KgaM9cik_P_ZlXvWnnO0f0bM9Wk647VbyrrUFMyTQTRyAlfk2O0oJ21LK2ZOR+YgszzEbMsfW0eECpGv4G_9EQ==&id=ff10659f-4b64-4fb5-ae4c-7302bc1f855a&resourceName=Assets)

1.4.1 version only shows support

**Comment by osy86** [comment]
What was it before?

**Comment by piotrasd** [comment]
that what was before 
![Zrzut ekranu 2019-09-7 o 12 45 04](https://user-images.githubusercontent.com/773012/64474477-59d0b000-d16d-11e9-880f-348421adcc56.png)

that line is missing, but I will check if that have any impact, latest Geekbench version free actually testing metal.

**Comment by osy86** [comment]
Interesting, I think this is due to the new pid spoof that changes the number of CU.

**Comment by piotrasd** [comment]
im changed in old way like here - https://github.com/osy86/HaC-Mini/issues/30
and still system showing me  Feature set macOS GPUFamily2 v1

**Comment by piotrasd** [comment]
GPU acceleration doesn't work over Intel or AMD with Safari etc. 
V2.0 Clean install (its weird if dosnt work with WG)

**Comment by osy86** [comment]
@piotrasd have you tried [resetting NVRAM](https://osy.gitbook.io/hac-mini-guide/post-installation/support#reset-nvram)?

**Comment by osy86** [comment]
@piotrasd Did the geekbench score change? Is this a real issue?

**Comment by osy86** [comment]
I've confirmed this is a non-issue.

In System Profiler, the code to display "Supported, feature set macOS GPUFamily2 v1" is done by matching the metal device to the GPU.

The code to do this is by calling `MTLCopyAllDevices()` and then comparing the `name` property with the Chipset Model. When we use WG to spoof the Chipset Model to say "Vega M", it does not change the string in `AMDMTLBronzeDriver` which says `AMD Radeon Polaris`. That means it fails to match the Metal device with the GPU device.

A "fix" for this would be to patch the string inside `AMDMTLBronzeDriver` to match. Might do this in Polaris22Fixup in the future. Alternatively, disable the model name spoofing.

However, there is no performance difference because this is just a string display issue.
