### ISSUE TITLE
 I want to keep my existing system.Can i?

### ISSUE THREAD

**Issue by tzh979215144** [osy86/HaC-Mini#48]
When I format a hard disk using the Disk Utility, can I format only a portion of the unused space? I want to keep my existing system.

**Comment by 22dm** [comment]
> > What's your existing system? If you are running Windows, using 'shrink volume' to get free space.
> 
> I have two systems, one is Windows 10 and the other is archlinux, thank you, I know how to allocate space. For my question, I mean that in addition to not formatting the entire hard disk, other operations follow the tutorial, can macos be successfully installed? More importantly, can the two systems that I originally exist boot properly?

Well, I also have Arch and Windows before I installed macOS. You can only "Erase" a single partition, not the whole disk, and install macOS on it. I believe you know how to do with the EFI partition to recover boot loader for Arch/Win since you're using Arch.

However, backup your data before doing anything is never a bad idea.

**Comment by tzh979215144** [comment]
> Well, I also have Arch and Windows before I installed macOS. You can only "Erase" a single partition, not the whole disk, and install macOS on it. I believe you know how to do with the EFI partition to recover boot loader for Arch/Win since you're using Arch.
> 
> However, backup your data before doing anything is never a bad idea.

Ok, thank you very much for your reply. I have successfully installed, although I am not using this tutorial. By the way, manjaro+i3wm is really easy to use.
