### ISSUE TITLE
Not seeing partition 1

### ISSUE THREAD

**Issue by Jase-NZ** [osy86/HaC-Mini#49]
Created usb installer, Ran package installer which was successful (check box for patching osx)

Nuc can see the usb stick but only shows one partition to boot from and you cannot boot from that partition. I tried another machine (Gigabyte motherboard) and it shows two partitions I am able to boot from either partition 0 or partition 1, If I select 0 it won't boot but if I select 1 the installer tries and boots. But partition 1 does not show as an option on the nuc to boot from

**Configuration**
- HaC Mini version [2.0]: 
- OSX version [10.14.6]: 
- NUC model [NUC8i7HNK]: 
- Boot SSD model and protocol [Samsung EVO 870 1TB, SATA]: 
- First DIMM model [Crucial DDR4-2666 16GB]: 
- Second DIMM model [Crucial DDR4-2666 16GB]: 
- Display port(s) used [HDMI]: 
- Display resolution(s) [1080p]: 
- Any TB3 devices: no
- Any USB devices: no

[Installer Log 13-Sep-2019.txt](https://github.com/osy86/HaC-Mini/files/3607400/Installer.Log.13-Sep-2019.txt)

**Comment by mspecbmw** [comment]
Seemed to be quite unstable with random reboots, appeared to be nvme related. Updated to Catlina latest beta and have not seen a reboot yet.

**Comment by kachunkachunk** [comment]
My NVMe has a preexisting installation of Manjaro which I'm fine blowing away. Is it a bug, or EFI-BIOS misconfiguration on our part, that makes it skip the OpenCore bootloader? Kind of weird.
I guess I could try using the EFI shell and seeing if that behaves differently.

**Comment by osy86** [comment]
> Seemed to be quite unstable with random reboots, appeared to be nvme related. Updated to Catlina latest beta and have not seen a reboot yet.

Is it this https://github.com/osy86/HaC-Mini/issues/22

**Comment by kachunkachunk** [comment]
Okay, determined that hammering the alt key to get the OpenCore boot menu was what I needed. This was irrespective of using the EFI shell to select the boot image. I guess a timer or something would help? Or is this nonsense?

**Comment by osy86** [comment]
OC is supposed to find the right partition through bless. There might be a bug there; I’ll have to reproduce it.

**Comment by kachunkachunk** [comment]
I wish I took a picture. But okay, one thing to mention is the boot entries looked to be different when a preexisting EFI installation existed on the NUC first. So, hitting alt would show option 1 as something I cannot remember, but it could be NONE or NULL or something along those lines. Option two was the installer, option three was reset NVRAM.

Upon getting through the first installer phase (erasing my existing Manjaro EFI install) and rebooting, hammering Alt again shows options 1 to boot from the USB EFI image, 2 to boot from another installer image, 3 for recovery, and 4 to reset NVRAM.

**Comment by mspecbmw** [comment]
> #22

Could very well be looks very similar, I have had it running overnight now on full load doing a lot of tasks and is still running ok this morning.

**Comment by mspecbmw** [comment]
You must have jinxed it because it just crashed. Was copying files from usb ssd to the second samsung 970 pro 1 TB drive.

panic(cpu 0 caller 0xffffff7f9175b4a7): nvme: "Fatal error occurred. CSTS=0x1 US[1]=0x0 US[0]=0x3c VID=0x144d DID=0xa808
. FW Revision=1B2QEXM7\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/IONVMeFamily/IONVMeFamily-470.0.10/IONVMeController.cpp:5258
Backtrace (CPU 0), Frame : Return Address
0xffffff83d0ed39e0 : 0xffffff800ef41b6b 
0xffffff83d0ed3a30 : 0xffffff800f078e95 
0xffffff83d0ed3a70 : 0xffffff800f06a8fe 
0xffffff83d0ed3ac0 : 0xffffff800eee8bb0 
0xffffff83d0ed3ae0 : 0xffffff800ef41257 
0xffffff83d0ed3be0 : 0xffffff800ef4163b 
0xffffff83d0ed3c30 : 0xffffff800f6d2879 
0xffffff83d0ed3ca0 : 0xffffff7f9175b4a7 
0xffffff83d0ed3cc0 : 0xffffff7f91746462 
0xffffff83d0ed3e20 : 0xffffff800f648119 
0xffffff83d0ed3e90 : 0xffffff800f648039 
0xffffff83d0ed3ec0 : 0xffffff800ef833b5 
0xffffff83d0ed3f40 : 0xffffff800ef82ee1 
0xffffff83d0ed3fa0 : 0xffffff800eee813e 
      Kernel Extensions in backtrace:
         com.apple.iokit.IONVMeFamily(2.1)[B9580874-AFA7-3149-B6E4-C2E0D866514E]@0xffffff7f91738000->0xffffff7f9177afff
            dependency: com.apple.driver.AppleMobileFileIntegrity(1.0.5)[7B2BEC82-3EFE-3735-BDF0-5C937031D263]@0xffffff7f8ff17000
            dependency: com.apple.iokit.IOPCIFamily(2.9)[67731E8F-F8D7-3AD5-9037-83FD26E4E3C7]@0xffffff7f8f90f000
            dependency: com.apple.driver.AppleEFINVRAM(2.1)[EE231B09-0A76-3AC7-BDB2-7170B66F7822]@0xffffff7f916d7000
            dependency: com.apple.iokit.IOStorageFamily(2.1)[0358FA7E-B2E2-3261-A143-1F7D546BC871]@0xffffff7f8fb76000
            dependency: com.apple.iokit.IOReportFamily(47)[8A456F86-9DC7-3659-9690-DF50846852BA]@0xffffff7f8f849000

BSD process name corresponding to current thread: kernel_task
Boot args: alcid=11 shikigva=32 shiki-id=Mac-BE088AF8C5EB4FA2 -disablegfxfirmware

Mac OS version:
19A558d

Kernel version:
Darwin Kernel Version 19.0.0: Sat Aug 31 18:49:12 PDT 2019; root:xnu-6153.11.15~8/RELEASE_X86_64
Kernel UUID: 7878452F-EDBA-3FDA-8430-29920E2E2C99
Kernel slide:     0x000000000ec00000
Kernel text base: 0xffffff800ee00000
__HIB  text base: 0xffffff800ed00000
System model name: Macmini8,1 (Mac-7BA5B2DFE22DDD8C)
System shutdown begun: NO
Panic diags file available: YES (0x0)

System uptime in nanoseconds: 32590128944091

**Comment by mspecbmw** [comment]
Just an observation on my part, When I have had the above crash I have been using any number of the usb 3 ports. Have just copied over 1 tb of data to nvme via the thunder bolt port with zero issue. 

A usb related issue perhaps ??

**Comment by osy86** [comment]
The error is inside MacOS. People have the same issue on macs with an adapter. Apple has to fix it.

**Comment by mspecbmw** [comment]
How do you mean with an adapter ?? , I have all the same nvme drives in my other hackintoshes with out issue. Even in my nuc817bh. 
Just trying to understand it.

**Comment by osy86** [comment]
There's adapters to get NVMe working inside a Mac. I think the issue is with the Intel PCH controller.

**Comment by mspecbmw** [comment]
One observation I have just found out and that is the temp that the nvme's are running at and I am wondering if a thermal cutout is causing the reboot.
I have two drive samsung 970 evo drives in and it was constantly rebooting. When I took one drive out it appeared to be stable with no rebooting. As soon as I put the other one back in within a few minutes it had rebooted. I notice the thermal pad only covers half each of the drives so i had some thermal pad here and cutting the one on the machine to size and adding a pad to the other drive so they are both completely covered I have not had a reboot since and temps are around the 47 - 55 mark.

I am enjoying trying stuff out so will see how this one goes.

![2D44FC92-A929-4BAA-AA10-D427B37F945E_1_105_c](https://user-images.githubusercontent.com/7828510/64900737-24850e80-d6e7-11e9-8774-bf5d0f518d81.jpeg)
![Screen Shot 2019-09-13 at 4 51 23 PM](https://user-images.githubusercontent.com/7828510/64900742-31096700-d6e7-11e9-931e-e48486832487.png)

**Comment by osy86** [comment]
Interesting theory, let me know how it goes

**Comment by mspecbmw** [comment]
2 hours in and constant use of final cut pro and zero reboots, nvme drives rise to a maximum of 75deg under heavy load.

Will give it 24 hours and see how we are looking.

**Comment by osy86** [comment]
For issues booting into Windows, see "Installing other OS" in https://osy.gitbook.io/hac-mini-guide/installation-guide/installation

**Comment by mspecbmw** [comment]
Only going to use osx on this no intention to putting windows on it.

**Comment by mspecbmw** [comment]
This has fixed the issue for me zero reboots with 2 drives under constant load for the lat 12 hours. 
My fix was pretty janky so I have got some decent nvme heat sinks coming so will retrofit those when when they arrive.

**Comment by kachunkachunk** [comment]
Good to know about the potential overheating. I noticed the poor thermal pad coverage as well. Even with just one, it's half-covered in my NUC8i7HVK.

**Comment by osy86** [comment]
Since the original issue was resolved, lets move the NVMe issue discussion to https://github.com/osy86/HaC-Mini/issues/22
